"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import type { LaboratoryEmployment, LaboratoryScenario, LaboratorySession } from "@/laboratory/types";
import styles from "@/components/laboratory.module.css";

type Preset = { presetId: string; label: string; description: string; expectedOutcome: string; scenario: LaboratoryScenario };
const LABELS = ["Synthetic Employer A", "Synthetic Employer B", "Synthetic Employer C", "Synthetic Employer D", "Synthetic Employer E", "Synthetic Employer F"];
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { cache: "no-store", headers: { "Content-Type": "application/json" }, ...init }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message ?? "The laboratory request failed."); return body as T; }

export function LaboratoryApp() {
  const [presets, setPresets] = useState<Preset[]>([]); const [session, setSession] = useState<LaboratorySession | null>(null); const [scenario, setScenario] = useState<LaboratoryScenario | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [confirm, setConfirm] = useState<"exit" | "account" | null>(null); const resultsRef = useRef<HTMLElement>(null);
  useEffect(() => { void (async () => { try { const list = await api<{ presets: Preset[] }>("/api/v1/laboratory/presets"); setPresets(list.presets); const created = await api<{ session: LaboratorySession }>("/api/v1/laboratory/sessions", { method: "POST", body: JSON.stringify({ presetId: "clean-history" }) }); setSession(created.session); setScenario(created.session.draft); } catch (cause) { setError(cause instanceof Error ? cause.message : "The laboratory could not start."); } })(); }, []);
  const edit = (change: (draft: LaboratoryScenario) => void) => setScenario((current) => { if (!current) return current; const next = structuredClone(current); change(next); return next; });
  async function create(presetId: string) { setBusy(true); setError(""); try { const result = await api<{ session: LaboratorySession }>("/api/v1/laboratory/sessions", { method: "POST", body: JSON.stringify({ presetId }) }); setSession(result.session); setScenario(result.session.draft); setConfirm(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Preset failed."); } finally { setBusy(false); } }
  async function run() { if (!session || !scenario) return; setBusy(true); setError(""); try { const saved = await api<{ session: LaboratorySession }>(`/api/v1/laboratory/sessions/${session.sessionId}`, { method: "PUT", body: JSON.stringify({ expectedDraftVersion: session.draftVersion, scenario }) }); const result = await api<{ session: LaboratorySession }>(`/api/v1/laboratory/sessions/${session.sessionId}/runs`, { method: "POST", body: JSON.stringify({ expectedDraftVersion: saved.session.draftVersion }) }); setSession(result.session); setScenario(result.session.draft); requestAnimationFrame(() => resultsRef.current?.focus()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Assessment failed."); } finally { setBusy(false); } }
  async function simulate(kind: "exit" | "account") { if (!session) return; setBusy(true); try { const employmentId = session.assessment?.issues.find(({ ruleId }) => ruleId === "R001")?.affectedEmploymentIds[0]; const path = kind === "exit" ? "simulate-exit-update" : "simulate-account-link"; const body = kind === "exit" ? { expectedDraftVersion: session.draftVersion, expectedSnapshotVersion: session.snapshotVersion, employmentId, exitDate: "2021-03-31", exitReason: "RESIGNATION", confirmed: true } : { expectedDraftVersion: session.draftVersion, expectedSnapshotVersion: session.snapshotVersion, targetAccountGroup: "A", confirmed: true }; const result = await api<{ session: LaboratorySession }>(`/api/v1/laboratory/sessions/${session.sessionId}/actions/${path}`, { method: "POST", body: JSON.stringify(body) }); setSession(result.session); setScenario(result.session.draft); setConfirm(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Simulation failed."); } finally { setBusy(false); } }
  function exportJson() { if (!scenario) return; const url = URL.createObjectURL(new Blob([JSON.stringify(scenario, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "pf-health-synthetic-scenario.json"; link.click(); URL.revokeObjectURL(url); }
  async function importJson(file: File) { try { const imported: unknown = JSON.parse(await file.text()); const result = await api<{ session: LaboratorySession }>("/api/v1/laboratory/sessions", { method: "POST", body: JSON.stringify({ scenario: imported }) }); setSession(result.session); setScenario(result.session.draft); } catch (cause) { setError(cause instanceof Error ? cause.message : "Import failed."); } }
  if (!scenario || !session) return <main className={styles.loading}><h1>Preparing the PF Record Laboratory…</h1>{error && <p role="alert">{error}</p>}</main>;
  const assessment = session.assessment;
  return <div className={styles.site}><header className={styles.header}><Link href="/" className={styles.brand}>PF Health</Link><span>PF Record Laboratory</span></header><div className={styles.notice}>Synthetic digital twin · Deterministic · No EPFO connection</div><main className={styles.labMain} id="main-content"><section className={styles.labIntro}><div><h1>Construct the record. Test the consequence.</h1><p>Modify a fictional history, then freeze a snapshot to see which facts drive each rule.</p></div><div className={styles.fileActions}><button onClick={exportJson}>Export JSON</button><label>Import JSON<input type="file" accept="application/json" onChange={(event) => event.target.files?.[0] && void importJson(event.target.files[0])}/></label></div></section>{error && <div className={styles.error} role="alert">{error}</div>}<div className={styles.workspace}>
    <section className={styles.editor} aria-labelledby="edit-heading"><div className={styles.sectionHead}><div><h2 id="edit-heading">Edit synthetic history</h2><p>Draft version {session.draftVersion}</p></div><select aria-label="Load preset" value={session.presetId === "imported" ? "" : session.presetId} onChange={(event) => void create(event.target.value)}><option value="" disabled>Imported scenario</option>{presets.map((preset) => <option key={preset.presetId} value={preset.presetId}>{preset.label}</option>)}</select></div><fieldset className={styles.workflow}><legend>Assessment workflow</legend><label><input name="laboratory-workflow" type="radio" checked={scenario.workflow === "TRANSFER"} onChange={() => edit((draft) => { draft.workflow = "TRANSFER"; })}/> Online transfer</label><label><input name="laboratory-workflow" type="radio" checked={scenario.workflow === "GENERAL_HEALTH"} onChange={() => edit((draft) => { draft.workflow = "GENERAL_HEALTH"; })}/> General health</label></fieldset>
      <div className={styles.employments}>{scenario.employments.map((employment, index) => <article className={styles.employment} key={employment.employmentId}><div className={styles.employmentHead}><div><span>{employment.status === "CURRENT" ? "Current" : "Previous"}</span><h3>{employment.employerLabel}</h3></div><div><button onClick={() => edit((draft) => { const source = draft.employments[index]; draft.employments.splice(index + 1, 0, { ...source, employmentId: `lab_emp-${crypto.randomUUID()}`, employerLabel: LABELS[draft.employments.length], status: "PREVIOUS" }); })} disabled={scenario.employments.length >= 6}>Duplicate</button><button onClick={() => edit((draft) => { draft.employments.splice(index, 1); })} disabled={scenario.employments.length <= 1 || employment.status === "CURRENT"}>Delete</button></div></div><div className={styles.fields}><label>Start date<input type="date" value={employment.startDate} onChange={(event) => edit((draft) => { draft.employments[index].startDate = event.target.value; })}/></label><label>Synthetic account<select value={employment.accountGroup} onChange={(event) => edit((draft) => { draft.employments[index].accountGroup = event.target.value as "A"|"B"|"C"; })}><option value="A">Synthetic account A</option><option value="B">Synthetic account B</option><option value="C">Synthetic account C</option></select></label>{employment.status === "PREVIOUS" && <><label>Exit date<input id={`exit-${employment.employmentId}`} type="date" value={employment.exitDate ?? ""} onChange={(event) => edit((draft) => { draft.employments[index].exitDate = event.target.value || null; if (!event.target.value) draft.employments[index].exitReason = null; })}/></label><label>Exit reason<select value={employment.exitReason ?? ""} onChange={(event) => edit((draft) => { draft.employments[index].exitReason = (event.target.value || null) as LaboratoryEmployment["exitReason"]; })}><option value="">Not recorded</option><option value="RESIGNATION">Resignation</option><option value="RETIREMENT">Retirement</option><option value="CESSATION_SHORT_SERVICE">Cessation (short service)</option><option value="OTHER_SYNTHETIC">Other synthetic reason</option></select></label></>}</div></article>)}</div><button className={styles.addButton} onClick={() => edit((draft) => { const index = draft.employments.length; draft.employments.splice(index - 1, 0, { employmentId: `lab_emp-${crypto.randomUUID()}`, employerLabel: LABELS[index], status: "PREVIOUS", startDate: "2017-04-01", exitDate: "2018-03-31", exitReason: "RESIGNATION", accountGroup: "A" }); })} disabled={scenario.employments.length >= 6}>+ Add previous employment</button><button className={styles.runButton} onClick={() => void run()} disabled={busy}>{busy ? "Running deterministic checks…" : "Run assessment"}</button></section>
    <section className={styles.results} aria-labelledby="results-heading" ref={resultsRef} tabIndex={-1} key={assessment?.assessmentId ?? "draft"}><div className={styles.sectionHead}><div><h2 id="results-heading">Results</h2><p>{assessment ? `Snapshot ${assessment.snapshotVersion} · ${assessment.ruleSet}` : "No authoritative snapshot yet"}</p></div>{assessment && <span className={`${styles.outcome} ${styles[assessment.outcome.toLowerCase()]}`}>{assessment.outcome.replaceAll("_", " ")}</span>}</div>{!assessment ? <div className={styles.empty}><h3>Draft is ready to test.</h3><p>Run the assessment to create a versioned result, evidence graph, actor plan, and audit event.</p></div> : <><ol className={styles.checks}>{assessment.checks.map((check) => <li key={check.ruleId}><span>{check.ruleId}</span><div><strong>{check.label}</strong><small>{check.reasonCode.replaceAll("_", " ")}</small></div><b>{check.status}</b></li>)}</ol><section className={styles.evidenceSection}><h2>Evidence</h2><p>{assessment.evidenceGraph.nodes.length} nodes · {assessment.evidenceGraph.edges.length} relationships</p><div className={styles.graph} role="img" aria-label="Evidence graph from employments through checks to issues"><div>{scenario.employments.map((item) => <span key={item.employmentId}>{item.employerLabel}</span>)}</div><i>→</i><div>{assessment.checks.map((item) => <span key={item.ruleId}>{item.ruleId} · {item.status}</span>)}</div><i>→</i><div>{assessment.issues.length ? assessment.issues.map((item) => <span key={item.issueId}>{item.title}</span>) : <span>No issue emitted</span>}</div></div><details><summary>Read the textual evidence trace</summary><ol>{assessment.evidenceGraph.trace.map((line) => <li key={line}>{line}</li>)}</ol></details></section><section className={styles.planSection}><h2>Actor plan</h2>{assessment.actorPlan.length === 0 ? <p>No correction plan is needed.</p> : assessment.actorPlan.map((action) => <article key={action.actionId}><span>{action.actor.replaceAll("_", " ")}</span><h3>{action.title}</h3><p>{action.description}</p>{action.kind === "SIMULATE_EXIT" && <button onClick={() => { document.getElementById(`exit-${action.employmentIds[0]}`)?.focus(); setConfirm("exit"); }}>Prepare simulated exit update</button>}{action.kind === "SIMULATE_ACCOUNT_LINK" && <button onClick={() => setConfirm("account")}>Prepare simulated account link</button>}</article>)}</section>{confirm && <section className={styles.confirm}><h2>Confirm the exact synthetic change</h2><p>{confirm === "exit" ? "Set exit date to 31 March 2021 with reason Resignation." : "Reassign every employment to Synthetic account A."} No real record will change.</p><div><button onClick={() => setConfirm(null)}>Cancel</button><button onClick={() => void simulate(confirm)}>Apply simulated change</button></div></section>}</>}</section>
  </div><p className={styles.boundary}>PF Health does not guarantee a transfer or claim outcome. Sessions are process-local and synthetic.</p></main></div>;
}
