"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { proposeExitUpdate, type ExitUpdateProposal } from "@/laboratory/proposals";
import type { LaboratoryEmployment, LaboratoryScenario, LaboratorySession } from "@/laboratory/types";
import styles from "@/components/laboratory.module.css";

type Preset = { presetId: string; label: string; description: string; expectedOutcome: string; scenario: LaboratoryScenario };
const LABELS = ["Synthetic Employer A", "Synthetic Employer B", "Synthetic Employer C", "Synthetic Employer D", "Synthetic Employer E", "Synthetic Employer F"];
type Confirmation = { kind: "exit"; proposal: ExitUpdateProposal } | { kind: "account" };
const CASE_FILE_TAB_PATH = "M1 25L10 8C12 3.5 16.5 1 22 1H116C125 1 132 5 137 14L144 25H1Z";
function clientEmploymentId() { const randomPart = typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`; return `lab_emp-${randomPart}`; }
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { cache: "no-store", headers: { "Content-Type": "application/json" }, ...init }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message ?? "The laboratory request failed."); return body as T; }

export function LaboratoryApp() {
  const [presets, setPresets] = useState<Preset[]>([]); const [session, setSession] = useState<LaboratorySession | null>(null); const [scenario, setScenario] = useState<LaboratoryScenario | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [confirm, setConfirm] = useState<Confirmation | null>(null); const resultsRef = useRef<HTMLElement>(null);
  useEffect(() => { void (async () => { try { const list = await api<{ presets: Preset[] }>("/api/v1/laboratory/presets"); setPresets(list.presets); const created = await api<{ session: LaboratorySession }>("/api/v1/laboratory/sessions", { method: "POST", body: JSON.stringify({ presetId: "clean-history" }) }); setSession(created.session); setScenario(created.session.draft); } catch (cause) { setError(cause instanceof Error ? cause.message : "The laboratory could not start."); } })(); }, []);
  const edit = (change: (draft: LaboratoryScenario) => void) => setScenario((current) => { if (!current) return current; const next = structuredClone(current); change(next); return next; });
  async function create(presetId: string) { setBusy(true); setError(""); try { const result = await api<{ session: LaboratorySession }>("/api/v1/laboratory/sessions", { method: "POST", body: JSON.stringify({ presetId }) }); setSession(result.session); setScenario(result.session.draft); setConfirm(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Preset failed."); } finally { setBusy(false); } }
  async function run() { if (!session || !scenario) return; if (scenario.employments.some(({ employerLabel }) => employerLabel.trim().length < 2)) { setError("Every employment needs a fictional employer label of at least two characters."); return; } setBusy(true); setError(""); try { const saved = await api<{ session: LaboratorySession }>(`/api/v1/laboratory/sessions/${session.sessionId}`, { method: "PUT", body: JSON.stringify({ expectedDraftVersion: session.draftVersion, scenario }) }); const result = await api<{ session: LaboratorySession }>(`/api/v1/laboratory/sessions/${session.sessionId}/runs`, { method: "POST", body: JSON.stringify({ expectedDraftVersion: saved.session.draftVersion }) }); setSession(result.session); setScenario(result.session.draft); setConfirm(null); requestAnimationFrame(() => resultsRef.current?.focus()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Assessment failed."); } finally { setBusy(false); } }
  async function simulate(confirmation: Confirmation) { if (!session) return; setBusy(true); setError(""); try { const isExit = confirmation.kind === "exit"; const path = isExit ? "simulate-exit-update" : "simulate-account-link"; const body = isExit ? { expectedDraftVersion: session.draftVersion, expectedSnapshotVersion: session.snapshotVersion, employmentId: confirmation.proposal.employmentId, exitDate: confirmation.proposal.exitDate, exitReason: confirmation.proposal.exitReason, confirmed: true } : { expectedDraftVersion: session.draftVersion, expectedSnapshotVersion: session.snapshotVersion, targetAccountGroup: "A", confirmed: true }; const result = await api<{ session: LaboratorySession }>(`/api/v1/laboratory/sessions/${session.sessionId}/actions/${path}`, { method: "POST", body: JSON.stringify(body) }); setSession(result.session); setScenario(result.session.draft); setConfirm(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Simulation failed."); } finally { setBusy(false); } }
  function prepareExit(employmentId: string) { if (!scenario) return; const proposal = proposeExitUpdate(scenario, employmentId); if (!proposal) { document.getElementById(`exit-${employmentId}`)?.focus(); setError("PF Health could not derive a safe exit date from this chronology. Edit the highlighted exit fields, then run the assessment again."); return; } setError(""); setConfirm({ kind: "exit", proposal }); }
  function exportJson() { if (!scenario) return; const url = URL.createObjectURL(new Blob([JSON.stringify(scenario, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "pf-health-synthetic-scenario.json"; link.click(); URL.revokeObjectURL(url); }
  async function importJson(file: File) { try { const imported: unknown = JSON.parse(await file.text()); const result = await api<{ session: LaboratorySession }>("/api/v1/laboratory/sessions", { method: "POST", body: JSON.stringify({ scenario: imported }) }); setSession(result.session); setScenario(result.session.draft); } catch (cause) { setError(cause instanceof Error ? cause.message : "Import failed."); } }
  if (!scenario || !session) return <main className={styles.loading}><h1>Preparing the PF Record Laboratory…</h1>{error && <p role="alert">{error}</p>}</main>;
  const assessment = session.assessment;
  const employmentEntries = scenario.employments.map((employment, index) => ({ employment, index }));
  const previousEntries = employmentEntries.filter(({ employment }) => employment.status === "PREVIOUS");
  const currentEntry = employmentEntries.find(({ employment }) => employment.status === "CURRENT")!;
  const renderEmployment = ({ employment, index }: (typeof employmentEntries)[number]) => <article className={styles.employment} key={employment.employmentId}><div className={styles.employmentHead}><h4>{employment.employerLabel}</h4>{employment.status === "PREVIOUS" && <button onClick={() => edit((draft) => { draft.employments.splice(index, 1); })} disabled={scenario.employments.length <= 1}>Delete</button>}</div><div className={styles.fields}><label className={styles.nameField}>Fictional employer label<input type="text" required maxLength={60} value={employment.employerLabel} onChange={(event) => edit((draft) => { draft.employments[index].employerLabel = event.target.value; })}/><small>Use a fictional label only. Do not enter a real employer name.</small></label><label>Start date<input type="date" value={employment.startDate} onChange={(event) => edit((draft) => { draft.employments[index].startDate = event.target.value; })}/></label><label>Synthetic account<select value={employment.accountGroup} onChange={(event) => edit((draft) => { draft.employments[index].accountGroup = event.target.value as "A"|"B"|"C"; })}><option value="A">Synthetic account A</option><option value="B">Synthetic account B</option><option value="C">Synthetic account C</option></select></label>{employment.status === "PREVIOUS" && <><label>Exit date<input id={`exit-${employment.employmentId}`} type="date" value={employment.exitDate ?? ""} onChange={(event) => edit((draft) => { draft.employments[index].exitDate = event.target.value || null; if (!event.target.value) draft.employments[index].exitReason = null; })}/></label><label>Exit reason<select value={employment.exitReason ?? ""} onChange={(event) => edit((draft) => { draft.employments[index].exitReason = (event.target.value || null) as LaboratoryEmployment["exitReason"]; })}><option value="">Not recorded</option><option value="RESIGNATION">Resignation</option><option value="RETIREMENT">Retirement</option><option value="CESSATION_SHORT_SERVICE">Cessation (short service)</option><option value="OTHER_SYNTHETIC">Other synthetic reason</option></select></label></>}</div></article>;
  return <div className={styles.site}><header className={styles.header}><Link href="/" className={styles.brand}>PF Health</Link><span>PF Record Laboratory</span></header><div className={styles.notice}>Synthetic digital twin · Deterministic · No EPFO connection</div><main className={styles.labMain} id="main-content"><section className={styles.labIntro}><div className={styles.heroCopy}><h1>Construct the record. Test the consequence.</h1><p>Build a fictional employment history, freeze a deterministic snapshot, and follow every fact from record to rule to action.</p><ol className={styles.heroFlow} aria-label="Laboratory workflow"><li><span>Edit</span>Shape the history</li><li><span>Run</span>Freeze a snapshot</li><li><span>Trace</span>Explain the result</li></ol></div><div className={styles.fileActions}><button onClick={exportJson}>Export JSON</button><label>Import JSON<input type="file" accept="application/json" onChange={(event) => event.target.files?.[0] && void importJson(event.target.files[0])}/></label></div></section>{error && <div className={styles.error} role="alert">{error}</div>}<div className={styles.workspace}>
    <section className={styles.editor} data-case-file="editor" aria-labelledby="edit-heading"><span className={styles.workspaceTab} data-workspace-tab="editor" aria-hidden="true"><svg viewBox="0 0 145 26" preserveAspectRatio="none"><path d={CASE_FILE_TAB_PATH}/></svg></span><div className={styles.sectionHead}><div><h2 id="edit-heading">Edit synthetic history</h2><p>Draft version {session.draftVersion}</p></div><select aria-label="Load preset" value={session.presetId === "imported" ? "" : session.presetId} onChange={(event) => void create(event.target.value)}><option value="" disabled>Imported scenario</option>{presets.map((preset) => <option key={preset.presetId} value={preset.presetId}>{preset.label}</option>)}</select></div><fieldset className={styles.workflow}><legend>Assessment workflow</legend><label><input name="laboratory-workflow" type="radio" checked={scenario.workflow === "TRANSFER"} onChange={() => edit((draft) => { draft.workflow = "TRANSFER"; })}/> Online transfer</label><label><input name="laboratory-workflow" type="radio" checked={scenario.workflow === "GENERAL_HEALTH"} onChange={() => edit((draft) => { draft.workflow = "GENERAL_HEALTH"; })}/> General health</label></fieldset>
      <div className={styles.employments}><section className={styles.previousGroup} data-employment-group="previous" aria-labelledby="previous-employments-heading"><div className={styles.employmentGroupHead}><div><h3 id="previous-employments-heading">Previous employments</h3><p>Earlier records are evaluated together in chronological order.</p></div><span>{previousEntries.length} {previousEntries.length === 1 ? "record" : "records"}</span></div>{previousEntries.map(renderEmployment)}<button className={styles.addButton} onClick={() => edit((draft) => { const index = draft.employments.length; draft.employments.splice(index - 1, 0, { employmentId: clientEmploymentId(), employerLabel: LABELS[index], status: "PREVIOUS", startDate: "2017-04-01", exitDate: "2018-03-31", exitReason: "RESIGNATION", accountGroup: "A" }); })} disabled={scenario.employments.length >= 6}>+ Add previous employment</button></section><section className={styles.currentGroup} data-employment-group="current" aria-labelledby="current-employment-heading"><div className={styles.employmentGroupHead}><div><h3 id="current-employment-heading">Current employment</h3><p>The active record anchors chronology and transfer checks.</p></div><span>Anchor record</span></div>{renderEmployment(currentEntry)}</section></div><button className={styles.runButton} onClick={() => void run()} disabled={busy}>{busy ? "Running deterministic checks…" : "Run assessment"}</button></section>
    <section className={styles.results} data-case-file="results" aria-labelledby="results-heading" ref={resultsRef} tabIndex={-1} key={assessment?.assessmentId ?? "draft"}>
      <span className={styles.workspaceTab} data-workspace-tab="results" aria-hidden="true"><svg viewBox="0 0 145 26" preserveAspectRatio="none"><path d={CASE_FILE_TAB_PATH}/></svg></span>
      <div className={styles.sectionHead}><div><h2 id="results-heading">Results</h2><p>{assessment ? `Snapshot ${assessment.snapshotVersion} · ${assessment.ruleSet}` : "No authoritative snapshot yet"}</p></div>{assessment && <span className={`${styles.outcome} ${styles[assessment.outcome.toLowerCase()]}`}>{assessment.outcome.replaceAll("_", " ")}</span>}</div>
      {!assessment ? <div className={styles.empty}><h3>Draft is ready to test.</h3><p>Run the assessment to create a versioned result, evidence graph, actor plan, and audit event.</p></div> : <>
        <ol className={styles.checks}>{assessment.checks.map((check) => <li key={check.ruleId}><span>{check.ruleId}</span><div><strong>{check.label}</strong><small>{check.reasonCode.replaceAll("_", " ")}</small></div><b>{check.status}</b></li>)}</ol>
        {assessment.issues.length > 0 && <section className={styles.issueSection} aria-labelledby="detected-issues-heading"><h2 id="detected-issues-heading">Detected issues <span>{assessment.issues.length}</span></h2><ul>{assessment.issues.map((issue) => <li key={issue.issueId}><strong>{issue.title}</strong><small>{issue.ruleId} · {issue.severity.replaceAll("_", " ")}</small></li>)}</ul></section>}
        <section className={styles.evidenceSection}><h2>Evidence</h2><p>{assessment.evidenceGraph.nodes.length} nodes · {assessment.evidenceGraph.edges.length} relationships</p><div className={styles.graph} role="img" aria-label="Evidence graph from employments through checks to issues"><div>{scenario.employments.map((item) => <span key={item.employmentId}>{item.employerLabel}</span>)}</div><i>→</i><div>{assessment.checks.map((item) => <span key={item.ruleId}>{item.ruleId} · {item.status}</span>)}</div><i>→</i><div>{assessment.issues.length ? assessment.issues.map((item) => <span key={item.issueId}>{item.title}</span>) : <span>No issue emitted</span>}</div></div><details><summary>Read the textual evidence trace</summary><ol>{assessment.evidenceGraph.trace.map((line) => <li key={line}>{line}</li>)}</ol></details></section>
        <section className={styles.planSection}><h2>Actor plan</h2>{assessment.actorPlan.length === 0 ? <p>No correction plan is needed.</p> : assessment.actorPlan.map((action) => <article key={action.actionId}><span>{action.actor.replaceAll("_", " ")}</span><h3>{action.title}</h3><p>{action.description}</p>{action.kind === "SIMULATE_EXIT" && <button onClick={() => prepareExit(action.employmentIds[0])}>Prepare simulated exit update</button>}{action.kind === "SIMULATE_ACCOUNT_LINK" && <button onClick={() => setConfirm({ kind: "account" })}>Prepare simulated account link</button>}</article>)}</section>
        {confirm && <section className={styles.confirm} data-confirmation-panel><h2>Confirm the exact synthetic change</h2>{confirm.kind === "exit" ? <><p>PF Health derived the date from the day before the next employment starts. Review it and choose the fictional exit reason before applying.</p><div className={styles.confirmFields}><label>Fictional employer<input value={confirm.proposal.employerLabel} readOnly/></label><label>Exit date<input type="date" value={confirm.proposal.exitDate} onChange={(event) => setConfirm({ kind: "exit", proposal: { ...confirm.proposal, exitDate: event.target.value } })}/></label><label>Exit reason<select aria-label="Confirmed exit reason" value={confirm.proposal.exitReason} onChange={(event) => setConfirm({ kind: "exit", proposal: { ...confirm.proposal, exitReason: event.target.value as ExitUpdateProposal["exitReason"] } })}><option value="">Choose a reason</option><option value="RESIGNATION">Resignation</option><option value="RETIREMENT">Retirement</option><option value="CESSATION_SHORT_SERVICE">Cessation (short service)</option><option value="OTHER_SYNTHETIC">Other synthetic reason</option></select></label></div></> : <p>Reassign every employment to Synthetic account A. No real record will change.</p>}<p className={styles.confirmBoundary}>This changes only the current synthetic session and automatically reruns all three rules.</p><div className={styles.confirmActions}><button onClick={() => setConfirm(null)}>Cancel</button><button onClick={() => void simulate(confirm)} disabled={busy || (confirm.kind === "exit" && (!confirm.proposal.exitDate || !confirm.proposal.exitReason))}>Apply simulated change</button></div></section>}
      </>}
    </section>
  </div><p className={styles.boundary}>PF Health does not guarantee a transfer or claim outcome. Sessions are process-local and synthetic.</p></main></div>;
}
